### PR TITLE
Cicd/cockpit rpms

### PR DESCRIPTION
**Pull request by Jean-Baptiste-Lasselle**
This PR provides the RPM Packages Definition for Gravitee Cockpit

This PR must not be validated before its bound PR https://github.com/gravitee-io/gravitee-cockpit/pull/617

### CODE REVIEW

**Comment by brasseld** [comment]
Hey @Jean-Baptiste-Lasselle 

I'm wondering how we are managing the license file when installing RPM for EE products / modules.
Any clue?

**Comment by loriepisicchio** [comment]
Hello @Jean-Baptiste-Lasselle. Any insights you can provide regarding @brasseld's comment ?

**Comment by Jean-Baptiste-Lasselle** [comment]
@brasseld @loriepisicchio true there : the RPM does not include the gravitee license I believe becaiuse I have been working on it by mutating AM RPM, so one thing to add there.

**Comment by brasseld** [comment]
@Jean-Baptiste-Lasselle @loriepisicchio can we setup a call to discuss that particular point?

**Comment by Jean-Baptiste-Lasselle** [comment]
* step 1 : 
  * test startup of cockpit
  * until we have error on cockpit license in the logs
* Step 2 : Add a final message "You have successfully installed Cockpit. The Cockpit license must now be installed to the ${LICENSE_FOLDER_PATH}"
* Step 3 : the gravitee license files must not be deleted with a yum upgrade or update. see https://graviteedevops.atlassian.net/browse/TEC-56

**Comment by gaetanmaisse** [comment]
Closing as Cockpit is now Saas only

**Pull request closed without merging**
