### PR TITLE
Fix: keep config files when upgrade

### PR DESCRIPTION
**Pull request by gcusnieux**
gravitee-io/issues#5287

### CODE REVIEW

**Review by gaetanmaisse — APPROVED** [review]
Tested locally with a migration from 3.17.0 to 3.17.1, updated config filed is saved: 
```
warning: /opt/graviteeio/apim/graviteeio-apim-gateway-3.17.0/config/gravitee.yml saved as /opt/graviteeio/apim/graviteeio-apim-gateway-3.17.0/config/gravitee.yml.rpmsave
```

image

**Review by leleueri — COMMENTED** [review]
With the new common bundle coming in 3.18. Do we have to add the `license` directory for AM & APIM in the same way as AE?

**Review by leleueri — CHANGES_REQUESTED** [review]
Maybe I did something wrong but is doesn't work for me on AM (tested with AM Gateway)

**Review by leleueri — APPROVED** [review]
Redo the test add works fine :+1:

**Review by remisultan — APPROVED** [review]
Same here with AE, LGTM

**Pull request merged**
